spring:
  datasource:
    url: jdbc:h2:mem:userdata
    username: sa
    password: sa
    driverClassName: org.h2.Driver

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: 'create-drop'
  h2:
    console:
      enabled: true
      path: /h2-console